#!/usr/bin/env perl

# PODNAME:  ess cli
# ABSTRACT: Email Sender Server CLI

use strict;
use warnings;

use File::Spec;
use File::Basename 'dirname';

use lib join '/', File::Spec->splitdir(dirname(__FILE__)), 'lib';
use lib join '/', File::Spec->splitdir(dirname(__FILE__)), '..', 'lib';

use Email::Sender::Server; 

our $VERSION = $Email::Sender::Server::VERSION || '0.0.0';

# $ENV{ESS_DATA} = '/path_to/data_directory/parent/folder';

$ARGV[0] ||= 'help';

Email::Sender::Server->run; # spit it out mickey-fickey
