---
abstract: 'Eventual Email Delivery System'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Sender-Server
requires:
  Class::Date: 0
  Data::Dumper: 0
  Emailesque: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec: 0
  Hash::Merge: 0
  Moo: 0
  utf8: 0
resources:
  bugtracker: https://github.com/alnewkirk/Email-Sender-Server/issues
  homepage: http://search.cpan.org/dist/Email-Sender-Server/
  repository: git://github.com/alnewkirk/Email-Sender-Server.git
version: 1.000001
