---
abstract: 'Eventual Email Delivery System'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-Sender-Server
requires:
  Class::Date: 0
  Data::Dumper: 0
  Data::Validate::Email: 0.04
  Email::MIME: 0
  Email::Sender: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  File::Type: 0
  IO::All: 0
  Validation::Class: 5.80
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Email-Sender-Server
  homepage: http://ana.io/
  repository: http://github.com/alnewkirk/Email-Sender-Server.git
version: 0.13
