use utf8;$VAR1 = {
          'created' => '2012-05-07 15:20:52',
          'attachments' => [],
          'headers' => [
                         {
                           'value' => 'Email-Sender-Server 0.00',
                           'name' => 'X-Mailer'
                         }
                       ],
          'transport' => {
                           'args' => {
                                       'sendmail' => '/usr/sbin/sendmail'
                                     },
                           'class' => 'Sendmail'
                         },
          'tags' => [],
          'message' => {
                         'to' => 'anewkirk@ana.io',
                         'body_text' => '[@CorePrep]
 
[Name]
[Version]
 
[Region  / prelude]
 
[Generic / SYNOPSIS]
[Generic / DESCRIPTION]
[Generic / OVERVIEW]

[Collect / EXPORTS]
command = export
 
[Collect / ATTRIBUTES]
command = attr
 
[Collect / METHODS]
command = method
 
[Leftovers]
 
[Region  / postlude]
 
[Authors]
[Legal]',
                         'subject' => 'testing',
                         'from' => 'awnstudio@gmail.com'
                       }
        };
