use utf8;$VAR1 = {
          'created' => '2012-05-07 15:19:43',
          'attachments' => [],
          'headers' => [
                         {
                           'value' => 'Email-Sender-Server 0.00',
                           'name' => 'X-Mailer'
                         }
                       ],
          'transport' => {
                           'args' => {
                                       'sendmail' => '/usr/sbin/sendmail'
                                     },
                           'class' => 'Sendmail'
                         },
          'tags' => [],
          'message' => {
                         'to' => 'anewkirk@ana.io',
                         'body_text' => 'this is a test',
                         'subject' => 'testing',
                         'from' => 'awnstudio@gmail.com'
                       }
        };
